# 冒号前面的不能动
check_whitelist: # 可乐鱼儿检测白名单
- 长春南溪湿地公园
- 娄底市妇幼保健院
- 娄底市妇幼保健院订阅号
- 中核华兴
- 绍兴银泰
- 昆明生态环境
- 京东企业业务
- 京东企业会员
- 最高人民检察院
- 雀巢专业在线
- 梅赛德斯-奔驰客户服务
- 广州中小学生体质健康
- 大连税务
- 江苏检察在线
- 中建八局
- 东莞市人民医院
- 蹦迪班长
- 新座驾
- 杭州文旅指南
- 乐威海
- 青春厦门
- 汉马科技集团
- 中建新疆建工五建
- 市话驿都
- 大理白族自治州妇幼保健院
- 中国探险协会
lt_config:
  ltck: # 一个-代表一个号,复制粘贴时注意对齐
    - ck: xxx
      name: xxx
    - ck: xxx
      name: xxx
      uid: UID_xxxxx
  blacklist: # 提现黑名单，填上面的name值
    - name1
    - name2
  delay_time: 30
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 1000 # 提现标准，1000即一块
ddz_config:
  ddzck:
  - ck: xxx
    name: xxx
  - ck: xxx
    name: xxx
    uid: UID_xxxxx
    zfb_account: '18888888888'
    zfb_name: 狗蛋
  delay_time: 30
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 8000
  zfb_account: '18888886666'
  zfb_name: 德华
kl_config:
  blacklist:
  - name1
  - name2
  delay_time: 30
  klck:
  - ck: 抓包的ck值
    name: 德华
  - ck: 抓包的ck值
    name: 彦祖
    uid: UID_xxx
    zfb_account: '18888888888'
    zfb_name: 狗蛋
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 8000
mm_config:
  blacklist:
  - name1
  - name2
  delay_time: 30
  max_workers: 3
  mmck:
  - ck: bbus=eyJpdiI6Ixxxxxxx
    name: ''
    zfb_account: ''
    zfb_name: ''
  pushable: 1
  sendable: 1
  txbz: 3000
mtz_config:
  blacklist:
  - name1
  - name2
  debug: 0
  delay_time: 40
  max_workers: 2
  mtzv2ck: name=xxx;ck=share:xxxx&name=xxx;ck=share:xxxx;uid=UID_xxxx
  pushable: 1
  sendable: 1
  total_num: 19
  txbz: 10000
pushconfig:
  appToken: ''
  topicids:
  - '123456'
qwbotkey: abcdeg
# 企业微信机器人key
ua_list:
- ua1
- ua2
xyy_config:
  blacklist: # 提现黑名单，填ck里第一个#号前面的的备注名
  - name1
  - name2
  debug: 1
  delay_time: 30
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 3000
  xyyck: 德华#抓包的ysmuid值&彦祖#抓包的ysmuid值#UID_xxx&狗蛋#ysmuid##支付宝账号#支付宝姓名
yu_config:
  blacklist:
  - '666'
  delay_time: 20
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 0.5
  yuck: # 每一个-为一个ck
  - ck: 抓包的ck值,PHxxxx=xxxxx
    name: 德华
  - ck: 抓包的ck值
    name: 彦祖
    uid: UID_xxx
    zfb_account: '18888888888'
    zfb_name: 狗蛋
