# 冒号前面的不能动
# ck优先从环境变量获取，如果环境变量有设置，在这里填的不会识别到


# 全局支付宝设置
zfb_config:
  zfb_account: 12345678@xx.com
  zdb_name: 德华

# 小赚帮设置
xzb_config:
  xzbck:
    - name: xxx
      ck: xiaozhuanbang_session=2
    - name: yyy
      ck: xiaozhuanbang_session=1
      uid: UID_xxxxx # wxpusher 一对一专属设置，不用一对一推送删除本行
      zfb_account: '18888888888' # 单号支付宝账号，如果是邮箱不用引号
      zfb_name: 狗蛋 # 单号支付宝姓名
  delay_time: 30
  max_workers: 5
  shuffle: 0 # 随机打乱ck顺序开关
  pushable: 1 # wxpusher推送开关，1开0关
  sendable: 1 # 企微推送开关，1开0关， 必须开启一项
  txbz: 3000 # 提现标准，低于8000分（0.8元）不提现

# 力天设置
lt_config:
  ltck:  # 填环境变量时多账号用&连接或换行或多条变量，填在此处一个-一个ck
  - name=德华;auth=Bxxxx
  - name=彦祖;auth=Bxxxxx
  blacklist: # 提现黑名单，设置的name不提现，填上面的name值
    - name1
    - name2
  delay_time: 30 # 线程启动延迟
  max_workers: 5 # 线程数
  pushable: 0  # wxpusher推送开关，1开0关，暂不用设置
  sendable: 0  # 企微推送开关，1开0关，暂不用设置
  txbz: 1000  # 提现标准，1000即一块
  shuffle: 0  # 是否每次跑都打乱顺序，1是0否

# 点点设置
ddz_config:
  ddzck:
  - ck: xxx # cookie所有值
    name: xxx # 备注
  - ck: xxx
    name: xxx
    uid: UID_xxxxx # wxpusher 一对一专属设置，不用一对一推送删除本行
    zfb_account: '18888888888' # 单号支付宝账号，如果是邮箱不用引号
    zfb_name: 狗蛋 # 单号支付宝姓名
  delay_time: 30
  max_workers: 5
  pushable: 1 # # wxpusher推送开关，1开0关
  sendable: 1 # 企微推送开关，1开0关， 必须开启一项
  txbz: 8000 # 提现标准，低于8000分（0.8元）不提现
  zfb_account: '18888886666'  # 全局支付宝账号
  zfb_name: 德华 # 全局支付宝姓名


# 可乐设置
kl_config:
  blacklist:
  - name1
  - name2
  delay_time: 30
#  check_num_list: # 检测序号列表，如第一篇为检测文章，则填入1，第61篇为检测文章则填61，一个-为一个序号。需手动删除本行#生效，否则每篇文章都推送
#  - 1
  klck:
  - ck: 抓包的ck值
    name: 德华
  - ck: 抓包的ck值
    name: 彦祖
    uid: UID_xxx
    zfb_account: '18888888888'
    zfb_name: 狗蛋
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 8000

# 猫猫设置
mm_config:
  blacklist:
  - name1
  - name2
  delay_time: 30
  max_workers: 3
  mmck:
  - ck: bbus=eyJpdiI6Ixxxxxxx
    name: ''
    zfb_account: ''
    zfb_name: ''
  pushable: 1
  sendable: 1
  txbz: 3000

# 每天赚设置
mtz_config:
  blacklist:
  - name1
  - name2
  debug: 0
  delay_time: 40
  max_workers: 2
  mtzv2ck: name=xxx;ck=share:xxxx&name=xxx;ck=share:xxxx;uid=UID_xxxx
  pushable: 1
  sendable: 1
  total_num: 19
  txbz: 10000

# wxpusher参数设置
pushconfig:
  appToken: ''
  topicids:
  - '123456'

# 企业微信机器人key
qwbotkey: abcdeg

# 自定义ua列表
ua_list:
- ua1
- ua2

# 小月月设置
xyy_config:
  blacklist: # 提现黑名单，填ck里第一个#号前面的的备注名
  - name1
  - name2
  debug: 1
  delay_time: 30
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 3000
  xyyck: 德华#抓包的ysmuid值&彦祖#抓包的ysmuid值#UID_xxx&狗蛋#ysmuid##支付宝账号#支付宝姓名

# 鱼儿设置
yu_config:
  interrupted: true
  blacklist:
  - '666'
  delay_time: 20
  max_workers: 5
  pushable: 1
  sendable: 1
  txbz: 0.5
  #check_num_list: # 检测序号列表，如第一篇为检测文章，则填入0，第61篇为检测文章则填60，一个-为一个序号。需手动删除本行#生效，否则每篇文章都推送
  #  - 0
  yuck: # 每一个-为一个ck
  - ck: 抓包的ck值,PHxxxx=xxxxx
    name: 德华
  - ck: 抓包的ck值
    name: 彦祖
    uid: UID_xxx
    zfb_account: '18888888888'
    zfb_name: 狗蛋
